### ISSUE TITLE
Commit signing key 

### ISSUE THREAD

**Issue by yochananmarqos** [BitPonyLLC/huekeys#20]
The `gnupg` package uses keyserver.ubuntu.com. Please upload your key there.

```
❯ gpg --search-keys 87A9206416E3D33B
gpg: data source: https://162.213.33.8:443
gpg: key "87A9206416E3D33B" not found on keyserver
gpg: keyserver search failed: Not found
```

**Comment by bradrf** [comment]
done! should be available in both keyserver.ubuntu.com and (popos default) keys.openpgp.org, now
